// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWeyVbQ9iiL-mftOdSgE8-SFDphXFdQ4',
    appId: '1:761544969:web:3e4162324956a35cdf13d8',
    messagingSenderId: '761544969',
    projectId: 'futurescape-e990a',
    authDomain: 'futurescape-e990a.firebaseapp.com',
    storageBucket: 'futurescape-e990a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAt_DWOKJ59Wqnanrw5Nzs83UQphG7DeQ',
    appId: '1:761544969:android:b5310cb896627784df13d8',
    messagingSenderId: '761544969',
    projectId: 'futurescape-e990a',
    storageBucket: 'futurescape-e990a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMyUqBoFvH82-at17Nu_dvSz7qYLlzut8',
    appId: '1:761544969:ios:23a20feb841a464edf13d8',
    messagingSenderId: '761544969',
    projectId: 'futurescape-e990a',
    storageBucket: 'futurescape-e990a.appspot.com',
    iosClientId: '761544969-cdilhhtl6sdq3fo7sgas90h4kcgljhge.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui',
  );
}
